// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaThruZero
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "ThruZero"
#define PLUGIN_HEADER     "mdaThruZero.h"
#include "_wrapper.cpp"
