// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaAmbience
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "Ambience"
#define PLUGIN_HEADER     "mdaAmbience.h"
#include "_wrapper.cpp"
