// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaOverdrive
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "Overdrive"
#define PLUGIN_HEADER     "mdaOverdrive.h"
#include "_wrapper.cpp"
