// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaLoudness
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "Loudness"
#define PLUGIN_HEADER     "mdaLoudness.h"
#include "_wrapper.cpp"
