// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaEPiano
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "EPiano"
#define PLUGIN_HEADER     "mdaEPiano.h"
#include "_wrapper.cpp"
