// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaCombo
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "Combo"
#define PLUGIN_HEADER     "mdaCombo.h"
#include "_wrapper.cpp"
