// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaLimiter
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "Limiter"
#define PLUGIN_HEADER     "mdaLimiter.h"
#include "_wrapper.cpp"
