// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaTestTone
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "TestTone"
#define PLUGIN_HEADER     "mdaTestTone.h"
#include "_wrapper.cpp"
