// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaMultiBand
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "MultiBand"
#define PLUGIN_HEADER     "mdaMultiBand.h"
#include "_wrapper.cpp"
