// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaTracker
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "Tracker"
#define PLUGIN_HEADER     "mdaTracker.h"
#include "_wrapper.cpp"
