// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaTalkBox
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "TalkBox"
#define PLUGIN_HEADER     "mdaTalkBox.h"
#include "_wrapper.cpp"
