// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaRezFilter
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "RezFilter"
#define PLUGIN_HEADER     "mdaRezFilter.h"
#include "_wrapper.cpp"
