// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaImage
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "Image"
#define PLUGIN_HEADER     "mdaImage.h"
#include "_wrapper.cpp"
