// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaBandisto
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "Bandisto"
#define PLUGIN_HEADER     "mdaBandisto.h"
#include "_wrapper.cpp"
