// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaJX10
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "JX10"
#define PLUGIN_HEADER     "mdaJX10.h"
#include "_wrapper.cpp"
