// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaVocInput
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "VocInput"
#define PLUGIN_HEADER     "mdaVocInput.h"
#include "_wrapper.cpp"
