// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaDetune
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "Detune"
#define PLUGIN_HEADER     "mdaDetune.h"
#include "_wrapper.cpp"
