// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaDubDelay
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "DubDelay"
#define PLUGIN_HEADER     "mdaDubDelay.h"
#include "_wrapper.cpp"
