// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaLeslie
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "Leslie"
#define PLUGIN_HEADER     "mdaLeslie.h"
#include "_wrapper.cpp"
