export { default } from './setBfree_DSP_Tonewheel_Organ.js';
export const meta         = {
  "uri": "http://gareus.org/oss/lv2/b_synth",
  "label": "setBfree_DSP_Tonewheel_Organ",
  "name": "setBfree DSP Tonewheel Organ",
  "exportName": "createsetBfree_DSP_Tonewheel_OrganPlugin",
  "ports": [
    {
      "index": 0,
      "symbol": "control",
      "name": "MIDI In",
      "dir": "input",
      "type": "midi",
      "legacy": false,
      "cv": false,
      "min": null,
      "max": null,
      "default": null
    },
    {
      "index": 1,
      "symbol": "notify",
      "name": "MIDI Out",
      "dir": "output",
      "type": "atom",
      "legacy": false,
      "cv": false,
      "min": null,
      "max": null,
      "default": null
    },
    {
      "index": 2,
      "symbol": "outL",
      "name": "Left Output",
      "dir": "output",
      "type": "audio",
      "legacy": false,
      "cv": false,
      "min": null,
      "max": null,
      "default": null
    },
    {
      "index": 3,
      "symbol": "outR",
      "name": "Right Output",
      "dir": "output",
      "type": "audio",
      "legacy": false,
      "cv": false,
      "min": null,
      "max": null,
      "default": null
    },
    {
      "index": 4,
      "symbol": "upper_drawbar_16",
      "name": "Upper Drawbar 16",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 8,
      "default": 8,
      "integer": true
    },
    {
      "index": 5,
      "symbol": "upper_drawbar_513",
      "name": "Upper Drawbar 5 1/3",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 8,
      "default": 8,
      "integer": true
    },
    {
      "index": 6,
      "symbol": "upper_drawbar_8",
      "name": "Upper Drawbar 8",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 8,
      "default": 6,
      "integer": true
    },
    {
      "index": 7,
      "symbol": "upper_drawbar_4",
      "name": "Upper Drawbar 4",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 8,
      "default": 0,
      "integer": true
    },
    {
      "index": 8,
      "symbol": "upper_drawbar_223",
      "name": "Upper Drawbar 2 2/3",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 8,
      "default": 0,
      "integer": true
    },
    {
      "index": 9,
      "symbol": "upper_drawbar_2",
      "name": "Upper Drawbar 2",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 8,
      "default": 0,
      "integer": true
    },
    {
      "index": 10,
      "symbol": "upper_drawbar_135",
      "name": "Upper Drawbar 1 3/5",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 8,
      "default": 0,
      "integer": true
    },
    {
      "index": 11,
      "symbol": "upper_drawbar_113",
      "name": "Upper Drawbar 1 1/3",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 8,
      "default": 0,
      "integer": true
    },
    {
      "index": 12,
      "symbol": "upper_drawbar_1",
      "name": "Upper Drawbar 1",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 8,
      "default": 0,
      "integer": true
    },
    {
      "index": 13,
      "symbol": "swell",
      "name": "Swell Pedal",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 1,
      "default": 1
    },
    {
      "index": 14,
      "symbol": "reverb_mix",
      "name": "Reverb Mix",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 1,
      "default": 0.1
    },
    {
      "index": 15,
      "symbol": "overdrive_enable",
      "name": "Overdrive Enable",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 1,
      "default": 1,
      "integer": true,
      "toggled": true
    },
    {
      "index": 16,
      "symbol": "overdrive_drive",
      "name": "Overdrive Drive",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 1,
      "default": 0.36
    },
    {
      "index": 17,
      "symbol": "overdrive_output",
      "name": "Overdrive Output",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 1,
      "default": 0.08
    },
    {
      "index": 18,
      "symbol": "overdrive_tone",
      "name": "Overdrive Tone",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 1,
      "default": 0.53
    }
  ]
};
export const wasmUrl      = new URL('./setBfree_DSP_Tonewheel_Organ.wasm',  import.meta.url).href;
export const processorUrl = new URL('./processor.js',      import.meta.url).href;
