// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaRingMod
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "RingMod"
#define PLUGIN_HEADER     "mdaRingMod.h"
#include "_wrapper.cpp"
