// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaStereo
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "Stereo"
#define PLUGIN_HEADER     "mdaStereo.h"
#include "_wrapper.cpp"
