// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaSplitter
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "Splitter"
#define PLUGIN_HEADER     "mdaSplitter.h"
#include "_wrapper.cpp"
