// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaDX10
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "DX10"
#define PLUGIN_HEADER     "mdaDX10.h"
#include "_wrapper.cpp"
