// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaRoundPan
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "RoundPan"
#define PLUGIN_HEADER     "mdaRoundPan.h"
#include "_wrapper.cpp"
