// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaShepard
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "Shepard"
#define PLUGIN_HEADER     "mdaShepard.h"
#include "_wrapper.cpp"
