// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaVocoder
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "Vocoder"
#define PLUGIN_HEADER     "mdaVocoder.h"
#include "_wrapper.cpp"
