// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaDither
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "Dither"
#define PLUGIN_HEADER     "mdaDither.h"
#include "_wrapper.cpp"
