// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaDegrade
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "Degrade"
#define PLUGIN_HEADER     "mdaDegrade.h"
#include "_wrapper.cpp"
