export { default } from './String_machine.js';
export const meta         = {
  "uri": "http://jpcima.sdf1.org/lv2/string-machine-mk2",
  "label": "String_machine",
  "name": "String machine",
  "exportName": "createString_machinePlugin",
  "ports": [
    {
      "index": 0,
      "symbol": "lv2_audio_out_1",
      "name": "Audio Output 1",
      "dir": "output",
      "type": "audio",
      "legacy": false,
      "cv": false,
      "min": null,
      "max": null,
      "default": null
    },
    {
      "index": 1,
      "symbol": "lv2_audio_out_2",
      "name": "Audio Output 2",
      "dir": "output",
      "type": "audio",
      "legacy": false,
      "cv": false,
      "min": null,
      "max": null,
      "default": null
    },
    {
      "index": 2,
      "symbol": "lv2_events_in",
      "name": "Events Input",
      "dir": "input",
      "type": "midi",
      "legacy": false,
      "cv": false,
      "min": null,
      "max": null,
      "default": null
    },
    {
      "index": 3,
      "symbol": "osc_detune",
      "name": "Oscillator detune",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 1,
      "default": 0.00159999995958
    },
    {
      "index": 4,
      "symbol": "osc_hp_cutoff_upper",
      "name": "Oscillator HP Cutoff 4'",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": -20,
      "max": 60,
      "default": 8
    },
    {
      "index": 5,
      "symbol": "osc_hp_cutoff_lower",
      "name": "Oscillator HP Cutoff 8'",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": -20,
      "max": 60,
      "default": 8
    },
    {
      "index": 6,
      "symbol": "osc_pwm_depth",
      "name": "Oscillator PWM Depth",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 100,
      "default": 0
    },
    {
      "index": 7,
      "symbol": "osc_pwm_frequency",
      "name": "Oscillator PWM Frequency",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0.10000000149,
      "max": 5,
      "default": 0.25,
      "logarithmic": true
    },
    {
      "index": 8,
      "symbol": "osc_enhance_upper",
      "name": "Oscillator enhance 4'",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 0.5,
      "default": 0
    },
    {
      "index": 9,
      "symbol": "osc_enhance_lower",
      "name": "Oscillator enhance 8'",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 0.5,
      "default": 0
    },
    {
      "index": 10,
      "symbol": "flt_lp_cutoff_upper",
      "name": "Filters LP Cutoff 4'",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": -20,
      "max": 120,
      "default": 5.19999980927
    },
    {
      "index": 11,
      "symbol": "flt_hp_cutoff_upper",
      "name": "Filters HP Cutoff 4'",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": -20,
      "max": 120,
      "default": 12.1999998093
    },
    {
      "index": 12,
      "symbol": "flt_lp_cutoff_lower",
      "name": "Filters LP Cutoff 8'",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": -20,
      "max": 120,
      "default": 16.3999996185
    },
    {
      "index": 13,
      "symbol": "flt_hp_cutoff_lower",
      "name": "Filters HP Cutoff 8'",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": -20,
      "max": 120,
      "default": -0.40000000596
    },
    {
      "index": 14,
      "symbol": "flt_hs_cutoff_eq",
      "name": "Filters HS Cutoff 4'",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": -20,
      "max": 120,
      "default": 24.7999992371
    },
    {
      "index": 15,
      "symbol": "flt_hs_boost_eq",
      "name": "Filters HS Boost 4'",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": -20,
      "max": 20,
      "default": 6
    },
    {
      "index": 16,
      "symbol": "mix_gain_upper",
      "name": "Mix Gain 4'",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": -20,
      "max": 0,
      "default": 0
    },
    {
      "index": 17,
      "symbol": "mix_gain_lower",
      "name": "Mix Gain 8'",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": -20,
      "max": 0,
      "default": 0
    },
    {
      "index": 18,
      "symbol": "env_attack",
      "name": "Envelope attack",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0.00999999977648,
      "max": 10,
      "default": 0.193900004029,
      "logarithmic": true
    },
    {
      "index": 19,
      "symbol": "env_hold",
      "name": "Envelope hold",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0.00999999977648,
      "max": 10,
      "default": 0.00999999977648,
      "logarithmic": true
    },
    {
      "index": 20,
      "symbol": "env_decay",
      "name": "Envelope decay",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0.00999999977648,
      "max": 10,
      "default": 10,
      "logarithmic": true
    },
    {
      "index": 21,
      "symbol": "env_sustain",
      "name": "Envelope sustain",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": -60,
      "max": 0,
      "default": 0
    },
    {
      "index": 22,
      "symbol": "env_release",
      "name": "Envelope release",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0.00999999977648,
      "max": 10,
      "default": 3,
      "logarithmic": true
    },
    {
      "index": 23,
      "symbol": "cho_enabled",
      "name": "Chorus enabled",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 1,
      "default": 1,
      "integer": true,
      "toggled": true
    },
    {
      "index": 24,
      "symbol": "cho_depth",
      "name": "Chorus global depth",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 100,
      "default": 100
    },
    {
      "index": 25,
      "symbol": "cho_rate1",
      "name": "Chorus rate 1",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 1,
      "max": 9,
      "default": 5.83459997177
    },
    {
      "index": 26,
      "symbol": "cho_depth1",
      "name": "Chorus depth 1",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 100,
      "default": 30.7099990845
    },
    {
      "index": 27,
      "symbol": "cho_rate2",
      "name": "Chorus rate 2",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0.10000000149,
      "max": 0.899999976158,
      "default": 0.583500027657
    },
    {
      "index": 28,
      "symbol": "cho_depth2",
      "name": "Chorus depth 2",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 100,
      "default": 90.5500030518
    },
    {
      "index": 29,
      "symbol": "cho_model",
      "name": "Chorus model",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 1,
      "default": 1,
      "integer": true,
      "enumeration": true,
      "scalePoints": [
        {
          "label": "Digital delay",
          "value": 0
        },
        {
          "label": "Analog bucket-brigade delay",
          "value": 1
        }
      ]
    },
    {
      "index": 30,
      "symbol": "master_gain",
      "name": "Master Gain",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": -60,
      "max": 20,
      "default": 3
    },
    {
      "index": 31,
      "symbol": "polyphony",
      "name": "Polyphony",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 1,
      "max": 32,
      "default": 16,
      "integer": true
    },
    {
      "index": 32,
      "symbol": "osc_current_detune_upper",
      "name": "Oscillator detune 4'",
      "dir": "output",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": -1,
      "max": 1,
      "default": null
    },
    {
      "index": 33,
      "symbol": "osc_current_detune_lower",
      "name": "Oscillator detune 8'",
      "dir": "output",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": -1,
      "max": 1,
      "default": null
    },
    {
      "index": 34,
      "symbol": "cho_current_phase1",
      "name": "Chorus phase 1",
      "dir": "output",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 6.28318548203,
      "default": null
    },
    {
      "index": 35,
      "symbol": "cho_current_phase2",
      "name": "Chorus phase 2",
      "dir": "output",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 6.28318548203,
      "default": null
    },
    {
      "index": 36,
      "symbol": "master_current_level1",
      "name": "Master level 1",
      "dir": "output",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": -100,
      "max": 100,
      "default": null
    },
    {
      "index": 37,
      "symbol": "master_current_level2",
      "name": "Master level 2",
      "dir": "output",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": -100,
      "max": 100,
      "default": null
    }
  ]
};
export const wasmUrl      = new URL('./String_machine.wasm',  import.meta.url).href;
export const processorUrl = new URL('./processor.js',      import.meta.url).href;
