export { default } from './JuceOPL.js';
export const meta         = {
  "uri": "https://github.com/jpcima/JuceOPL#instrument",
  "label": "JuceOPL",
  "name": "JuceOPL",
  "exportName": "createJuceOPLPlugin",
  "ports": [
    {
      "index": 0,
      "symbol": "midi_in",
      "name": "MIDI In",
      "dir": "input",
      "type": "midi",
      "legacy": false,
      "cv": false,
      "min": null,
      "max": null,
      "default": null
    },
    {
      "index": 1,
      "symbol": "out_l",
      "name": "Audio Out L",
      "dir": "output",
      "type": "audio",
      "legacy": false,
      "cv": false,
      "min": null,
      "max": null,
      "default": null
    },
    {
      "index": 2,
      "symbol": "out_r",
      "name": "Audio Out R",
      "dir": "output",
      "type": "audio",
      "legacy": false,
      "cv": false,
      "min": null,
      "max": null,
      "default": null
    },
    {
      "index": 3,
      "symbol": "carrier_wave",
      "name": "Carrier Wave",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 7,
      "default": 0,
      "integer": true
    },
    {
      "index": 4,
      "symbol": "modulator_wave",
      "name": "Modulator Wave",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 7,
      "default": 2,
      "integer": true
    },
    {
      "index": 5,
      "symbol": "carrier_multiplier",
      "name": "Carrier Frequency Multiplier",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 15,
      "default": 1,
      "integer": true
    },
    {
      "index": 6,
      "symbol": "modulator_multiplier",
      "name": "Modulator Frequency Multiplier",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 15,
      "default": 2,
      "integer": true
    },
    {
      "index": 7,
      "symbol": "carrier_attenuation",
      "name": "Carrier Attenuation",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 63,
      "default": 9,
      "integer": true
    },
    {
      "index": 8,
      "symbol": "modulator_attenuation",
      "name": "Modulator Attenuation",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 63,
      "default": 26,
      "integer": true
    },
    {
      "index": 9,
      "symbol": "carrier_tremolo",
      "name": "Carrier Tremolo",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 1,
      "default": 0,
      "integer": true
    },
    {
      "index": 10,
      "symbol": "carrier_vibrato",
      "name": "Carrier Vibrato",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 1,
      "default": 0,
      "integer": true
    },
    {
      "index": 11,
      "symbol": "modulator_tremolo",
      "name": "Modulator Tremolo",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 1,
      "default": 0,
      "integer": true
    },
    {
      "index": 12,
      "symbol": "modulator_vibrato",
      "name": "Modulator Vibrato",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 1,
      "default": 0,
      "integer": true
    },
    {
      "index": 13,
      "symbol": "carrier_keyscale_level",
      "name": "Carrier Keyscale Level",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 3,
      "default": 0,
      "integer": true
    },
    {
      "index": 14,
      "symbol": "modulator_keyscale_level",
      "name": "Modulator Keyscale Level",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 3,
      "default": 0,
      "integer": true
    },
    {
      "index": 15,
      "symbol": "algorithm",
      "name": "Algorithm",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 1,
      "default": 0,
      "integer": true
    },
    {
      "index": 16,
      "symbol": "modulator_feedback",
      "name": "Modulator Feedback",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 7,
      "default": 0,
      "integer": true
    },
    {
      "index": 17,
      "symbol": "carrier_attack",
      "name": "Carrier Attack",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 15,
      "default": 8,
      "integer": true
    },
    {
      "index": 18,
      "symbol": "modulator_attack",
      "name": "Modulator Attack",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 15,
      "default": 8,
      "integer": true
    },
    {
      "index": 19,
      "symbol": "carrier_velocity_sensitivity",
      "name": "Carrier Velocity Sensitivity",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 2,
      "default": 0,
      "integer": true
    },
    {
      "index": 20,
      "symbol": "modulator_velocity_sensitivity",
      "name": "Modulator Velocity Sensitivity",
      "dir": "input",
      "type": "control",
      "legacy": false,
      "cv": false,
      "min": 0,
      "max": 2,
      "default": 0,
      "integer": true
    }
  ]
};
export const wasmUrl      = new URL('./JuceOPL.wasm',  import.meta.url).href;
export const processorUrl = new URL('./processor.js',      import.meta.url).href;
