#!/usr/bin/env node
/**
 * Set up plugin directories for mda-lv2 instruments.
 *
 * For each mda instrument:
 *   1. Creates plugins/mda_<Id>/ with manifest.ttl + plugin TTL
 *   2. Copies shared LVZ files (wrapper, audioeffectx, etc.)
 *   3. Copies plugin-specific source files
 *   4. Generates a unity-build entry file (mda_<Id>_lv2.cpp)
 *
 * The unity file sets PLUGIN_CLASS / URI_PREFIX / PLUGIN_URI_SUFFIX / PLUGIN_HEADER
 * and #includes the plugin and wrapper sources — avoiding command-line quoting issues
 * with string-literal defines.
 *
 * Usage:
 *   node scripts/setup-mda-lv2.js
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync, copyFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const ROOT    = join(dirname(fileURLToPath(import.meta.url)), '..');
const MDA     = join(ROOT, 'mda-lv2');
const PLUGINS = join(ROOT, 'plugins');

if (!existsSync(MDA)) {
    console.error('mda-lv2 not found. Run: git clone https://github.com/mod-audio/mda-lv2.git');
    process.exit(1);
}

// Instruments only — effects go into LADSPA catalog later
const INSTRUMENTS = [
    { id: 'DX10',    cls: 'mdaDX10',    desc: 'FM synthesizer, 8-voice polyphonic' },
    { id: 'JX10',    cls: 'mdaJX10',    desc: 'Virtual analog polysynth, 8-voice' },
    { id: 'EPiano',  cls: 'mdaEPiano',  desc: 'Electric piano (Rhodes/Wurlitzer style)' },
    { id: 'Piano',   cls: 'mdaPiano',   desc: 'Acoustic piano physical model' },
    { id: 'SubSynth',cls: 'mdaSubSynth',desc: 'Sub-bass synthesizer' },
    { id: 'BeatBox', cls: 'mdaBeatBox', desc: 'Drum machine / beat generator' },
];

// Shared LVZ files copied into every plugin directory (prefixed _ to skip auto-detect)
const LVZ_SHARED = [
    { src: join(MDA, 'lvz', 'wrapper.cpp'),      dst: '_wrapper.cpp' },
    { src: join(MDA, 'lvz', 'audioeffectx.h'),   dst: 'audioeffectx.h' },
    { src: join(MDA, 'lvz', 'AudioEffect.hpp'),  dst: 'AudioEffect.hpp' },
    { src: join(MDA, 'src', 'lv2_programs.h'),   dst: 'lv2_programs.h' },
];

const URI_PREFIX = 'http://moddevices.com/plugins/mda/';

const newEntries = [];

for (const inst of INSTRUMENTS) {
    const pluginId  = `mda_${inst.id}`;
    const pluginDir = join(PLUGINS, pluginId);
    const bundleDir = join(MDA, 'bundles', `mod-mda-${inst.id}.lv2`);
    const ttlFile   = `${inst.id}.ttl`;

    if (!existsSync(bundleDir)) {
        console.warn(`⚠ Bundle not found: ${bundleDir} — skipping`);
        continue;
    }

    mkdirSync(pluginDir, { recursive: true });
    console.log(`▶  ${pluginId}`);

    // 1. Generate manifest.ttl from manifest.ttl.in (replace @LIB_EXT@ placeholder)
    const templatePath = join(bundleDir, 'manifest.ttl.in');
    if (existsSync(templatePath)) {
        const manifest = readFileSync(templatePath, 'utf8')
            .replace(/@LIB_EXT@/g, '.so');
        writeFileSync(join(pluginDir, 'manifest.ttl'), manifest);
        console.log('   ✓ manifest.ttl');
    } else {
        console.warn('   ⚠ no manifest.ttl.in — skipping');
        continue;
    }

    // 2. Copy plugin TTL
    const ttlSrc = join(bundleDir, ttlFile);
    if (existsSync(ttlSrc)) {
        copyFileSync(ttlSrc, join(pluginDir, ttlFile));
        console.log(`   ✓ ${ttlFile}`);
    }

    // 3. Copy plugin source files
    for (const ext of ['.cpp', '.h']) {
        const f = `${inst.cls}${ext}`;
        const src = join(MDA, 'src', f);
        if (existsSync(src)) {
            copyFileSync(src, join(pluginDir, f));
            console.log(`   ✓ ${f}`);
        }
    }
    // EPiano and Piano have separate data headers
    for (const dataHdr of [`${inst.cls}Data.h`]) {
        const src = join(MDA, 'src', dataHdr);
        if (existsSync(src)) {
            copyFileSync(src, join(pluginDir, dataHdr));
            console.log(`   ✓ ${dataHdr}`);
        }
    }

    // 4. Copy shared LVZ files
    for (const { src, dst } of LVZ_SHARED) {
        if (existsSync(src)) {
            copyFileSync(src, join(pluginDir, dst));
        }
    }
    console.log('   ✓ lvz shared files');

    // 5. Generate wrapper entry file.
    //    Sets PLUGIN_* defines and includes _wrapper.cpp as an implementation
    //    unit. The plugin .cpp is compiled as a separate source so the plugin
    //    header is never included twice in the same translation unit.
    const wrapperFile = `mda_${inst.id}_lv2.cpp`;
    const wrapperSrc  = `\
// Auto-generated by setup-mda-lv2.js — do not edit
#define PLUGIN_CLASS      ${inst.cls}
#define URI_PREFIX        "${URI_PREFIX}"
#define PLUGIN_URI_SUFFIX "${inst.id}"
#define PLUGIN_HEADER     "${inst.cls}.h"
#include "_wrapper.cpp"
`;
    writeFileSync(join(pluginDir, wrapperFile), wrapperSrc);
    console.log(`   ✓ ${wrapperFile}`);

    newEntries.push({
        id:          pluginId,
        description: inst.desc,
        sources:     [wrapperFile, `${inst.cls}.cpp`],
    });
}

// Print instruments.json entries to add
console.log('\n── Add to plugins/instruments.json ──────────────────────────────\n');
console.log(JSON.stringify(newEntries, null, 2));
