// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaTransient
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "Transient"
#define PLUGIN_HEADER     "mdaTransient.h"
#include "_wrapper.cpp"
