// Auto-generated by setup-mda-lv2.js — do not edit
#define PLUGIN_CLASS      mdaPiano
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "Piano"
#define PLUGIN_HEADER     "mdaPiano.h"
#include "_wrapper.cpp"
