// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaRePsycho
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "RePsycho"
#define PLUGIN_HEADER     "mdaRePsycho.h"
#include "_wrapper.cpp"
