// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaDelay
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "Delay"
#define PLUGIN_HEADER     "mdaDelay.h"
#include "_wrapper.cpp"
