// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaDeEss
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "DeEss"
#define PLUGIN_HEADER     "mdaDeEss.h"
#include "_wrapper.cpp"
