// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaDynamics
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "Dynamics"
#define PLUGIN_HEADER     "mdaDynamics.h"
#include "_wrapper.cpp"
