// Auto-generated by setup-mda-lv2.js — do not edit
#define PLUGIN_CLASS      mdaSubSynth
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "SubSynth"
#define PLUGIN_HEADER     "mdaSubSynth.h"
#include "_wrapper.cpp"
