// Auto-generated by setup-mda-lv2.js. Do not edit.
#define PLUGIN_CLASS      mdaBeatBox
#define URI_PREFIX        "http://moddevices.com/plugins/mda/"
#define PLUGIN_URI_SUFFIX "BeatBox"
#define PLUGIN_HEADER     "mdaBeatBox.h"
#include "_wrapper.cpp"
